USE [master]
GO

/****** Object:  Database [EfinanceTeste]    Script Date: 23/09/2020 11:29:56 ******/
CREATE DATABASE [EfinanceTeste]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'EfinanceTeste', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\EfinanceTeste.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'EfinanceTeste_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\EfinanceTeste_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EfinanceTeste].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [EfinanceTeste] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [EfinanceTeste] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [EfinanceTeste] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [EfinanceTeste] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [EfinanceTeste] SET ARITHABORT OFF 
GO

ALTER DATABASE [EfinanceTeste] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [EfinanceTeste] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [EfinanceTeste] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [EfinanceTeste] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [EfinanceTeste] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [EfinanceTeste] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [EfinanceTeste] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [EfinanceTeste] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [EfinanceTeste] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [EfinanceTeste] SET  DISABLE_BROKER 
GO

ALTER DATABASE [EfinanceTeste] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [EfinanceTeste] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [EfinanceTeste] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [EfinanceTeste] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [EfinanceTeste] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [EfinanceTeste] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [EfinanceTeste] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [EfinanceTeste] SET RECOVERY FULL 
GO

ALTER DATABASE [EfinanceTeste] SET  MULTI_USER 
GO

ALTER DATABASE [EfinanceTeste] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [EfinanceTeste] SET DB_CHAINING OFF 
GO

ALTER DATABASE [EfinanceTeste] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [EfinanceTeste] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [EfinanceTeste] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [EfinanceTeste] SET QUERY_STORE = OFF
GO

ALTER DATABASE [EfinanceTeste] SET  READ_WRITE 
GO

